### ISSUE TITLE
Descriptor values?

### ISSUE THREAD

**Issue by underfitting** [ducha-aiki/hesaff-pytorch#2]
I ran feature_extractor.py and got results like below:

>1.0
>906
>411.1280822754 216.7289428711 0.0000048985 0.0000001165 0.0000061334
>398.0391540527 505.0095214844 0.0103844600 0.0009393070 0.0077745551
>342.8026428223 414.6062316895 0.0001460895 0.0000266796 0.0000589753
>409.6105346680 654.5926513672 0.0000042293 0.0000002372 0.0000030523
>439.0032958984 316.9766540527 0.0062913978 -0.0001653244 0.0018022966
>...

I think this only shows affine regions. Can I get descriptor values for each region (n-d features) like hesamp code?

EDIT:

I read readme and I did:

1. got patches with "patches = extract_patches(x, LAFs, PS = self.PS)"
2. processed "forward" of SIFTNet for each patch

I think I solved it, but did I do it correctly?

**Comment by ducha-aiki** [comment]
Yes, you did correctly. This would describe "upright" patches as in hesamp. This means that patches would be assumed to preserved "gravity" vector, which is common for retrieval setup like buildings etc. If you dataset has rotations, you may want to use some patch orientation estimation.

Btw, I would recommend you to use HardNet instead of SIFT, as in https://github.com/ducha-aiki/affnet/blob/master/examples/hesaffnet/WBS%20demo.ipynb

**Comment by underfitting** [comment]
Thank you. I get it!  I will try hardnet.

Btw, will you share the codes for retrieval tasks? (BoW, QE, HQE, MA)
Or, if you use some libraries, can you tell me about that?

**Comment by ducha-aiki** [comment]
Unfortunately, no. They are lab`s proprietary mess.
But I can recommend you this library: https://gitlab.com/vgg/vise

**Comment by underfitting** [comment]
I see. Thank you for recommendation!
